language: node_js
node_js:
  - "lts/*"
before_install:
  - git config --local user.name "Kristaps Grinbergs"
  - git config --local user.email "fassko@gmail.com"
install: skip
script:
  - node index.js
  - DATE=`date "+%d.%m.%Y"`
  - git commit CV-Kristaps-Grinbergs.pdf CV-Kristaps-Grinbergs.html -m "Generated PDF ${DATE}"
  - git push "https://${GITHUB_TOKEN}@github.com/fassko/cv.git" master > /dev/null 2>&1
