language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn install
install: skip
script:
  - markdown-pdf --out CV-Kristaps-Grinbergs.pdf README.md
  - DATE=`date "+%d.%m.%Y"`
  - git commit CV-Kristaps-Grinbergs.pdf -m "Generated PDF ${DATE}"
  - git push origin master
