language: node_js
node_js:
  - "lts/*"
before_install:
  - git config --local user.name "Kristaps Grinbergs"
  - git config --local user.email "fassko@gmail.com"
install: skip
script:
  - npm install mdpdf -g
  - mdpdf README.md CV-Kristaps-Grinbergs.pdf
  - DATE=`date "+%d.%m.%Y %H %H:%M:%S"`
  - git commit CV-Kristaps-Grinbergs.pdf -m "Generated PDF ${DATE}"
  - git remote add origin-cv https://${GITHUB_TOKEN}@github.com/fassko/cv.git > /dev/null 2>&1
  - git push origin-cv master
