language: node_js
node_js:
  - "lts/*"
before_install:
  - git config --local user.name "Kristaps Grinbergs"
  - git config --local user.email "fassko@gmail.com"
install: skip
script:
  - git remote rm origin
  - git remote add github "https://${GITHUB_TOKEN}@github.com/fassko/cv.git"
  - git fetch github
  - git checkout --track github/master
  - npm install mdpdf -g
  - mdpdf README.md CV-Kristaps-Grinbergs.pdf
  - DATE=`date "+%d.%m.%Y %H %H:%M:%S"`
  - git commit CV-Kristaps-Grinbergs.pdf -m "Generated PDF ${DATE}"
  - git push github master
